definitions:
  controllers.CreateKYCAddressRequest:
    properties:
      district:
        type: string
      municipality:
        type: string
      province:
        type: string
      ward_number:
        type: string
    required:
    - district
    - province
    - ward_number
    type: object
  controllers.CreateKYCRequest:
    properties:
      address:
        $ref: '#/definitions/controllers.CreateKYCAddressRequest'
      firm_registered:
        type: boolean
      full_name:
        type: string
      is_kyc:
        type: boolean
      mobile_number:
        type: string
      service:
        $ref: '#/definitions/controllers.CreateKYCServiceRequest'
      working_area:
        $ref: '#/definitions/controllers.CreateKYCWorkingAreaRequest'
    required:
    - address
    - full_name
    - mobile_number
    - service
    - working_area
    type: object
  controllers.CreateKYCServiceRequest:
    properties:
      service_name:
        type: string
    required:
    - service_name
    type: object
  controllers.CreateKYCWorkingAreaRequest:
    properties:
      activities:
        items:
          type: string
        type: array
      area_name:
        type: string
    required:
    - activities
    - area_name
    type: object
  controllers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  controllers.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  controllers.UserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  gin.H:
    additionalProperties: {}
    type: object
info:
  contact: {}
paths:
  /user/kyc:
    post:
      consumes:
      - application/json
      description: Create KYC (Know Your Customer) record.
      parameters:
      - description: KYC details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateKYCRequest'
      produces:
      - application/json
      responses:
        "200":
          description: KYC created successfully
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Failed to read body or create KYC
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create KYC
      tags:
      - KYC
  /user/login:
    post:
      consumes:
      - application/json
      description: Log in a user.
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created Successfully
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
      summary: User login
      tags:
      - Users
  /user/signup:
    post:
      consumes:
      - application/json
      description: Create a new user.
      parameters:
      - description: User information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created Successfully
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
      summary: Create new user
      tags:
      - Users
swagger: "2.0"
